name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.101
    - name: Restore dependencies
      run: dotnet restore ClassLibraryProject
    - name: Build
      run: dotnet build ClassLibraryProject
    - name: Test
      run: dotnet test ClassLibraryProject/StringLibraryTest/StringLibraryTest.csproj
