name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: check dir
      run: pwd
    - name: listdir
      run: ls -al
    - name: check dir 2
      run: cd ..
    - name: listdir 2
      run: ls -al 
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test ClassLibraryProject/StringLibraryTest/StringLibraryTest.csproj
