name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Changing directory
      run: cd ~
    - name: Check directory
      run: pwd
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.101
    - name: Restore dependencies
      run: dotnet restore ClassLibraryProject/ClassLibraryProject.csproj
    - name: Build
      run: dotnet build ClassLibraryProject/ClassLibraryProject.csproj
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Changing directory
      run: cd ~
    - name: Check directory
      run: pwd
    - name: Test
      run: dotnet test ClassLibraryProject/StringLibraryTest/StringLibraryTest.csproj
